src/components/content/TableOfContent.vue
src/content/tech/code.md
src/pages/blogs/[...slug].vue

- 技術ブログの目次を動的に取得できないかと調査していたところ、`queryContent` から取得した本文から取得できることがわかったので、表示するように

マークダウンの目次を表示するように

---

.github/workflows/code-analysis.yml
.github/workflows/composite/setup/action.yml

- これから長期でブログを運用していくので、今のうちに lint の CI を導入する

lint CI 導入

---

.github/workflows/create-release-pr.yml

- main ブランチで動作確認を取ったところ、修正すべき箇所が見つかったので、まとめる

release pr 作成の github actions を修正

---

.github/workflows/deploy.yml

- デプロイを自動化したいので、リリース PR をマージしたときに本番反映されるように

deploy の github workflow を追加

---

src/content/tech/avoid-reject.md
src/content/tech/code.md
src/content/tech/each-active-model-serializer-pass-argument.md
src/content/tech/effective-way-to-register-external-module-func.md
src/content/tech/generate-release-note-workflow.md
src/content/tech/golang-interface-tips.md
src/content/tech/google-app-script-writen-in-es6.md
src/content/tech/google-photo-slack-bot.md
src/content/tech/increase-filesize-encoded-in-base64.md
src/content/tech/nuxtjs-animation.md
src/content/tech/shift-reminder.md
src/content/tech/state-notifier-unit-test.md
src/content/tech/to-rubyists-learning-golang.md
src/content/tech/v-model-in-custom-component.md
src/content/tech/vee-validate-custom-rule.md
src/pages/posts/categories/[category]/[page].vue

- 記事のカテゴリは複数なので、複数系の categories に修正する

記事のカテゴリを複数持つので、categories にキーを変更

---

package.json
pnpm-lock.yaml
src/server/routes/sitemap.xml.ts
utils/config/nitro/getContentRoutes.ts

- SEO 対策として、 sitemap を返す処理とパスを追加。
- 一旦箱だけ用意して、中身のチューニングについては、リリースしたあと適宜改善していく

sitemap を返す処理とパスを追加

---

.github/workflows/code-analysis.yml
.github/workflows/composite/setup/action.yml

- code-analysis で修正する箇所をまとめた
- キャッシュの生成材料のファイルがなかったの を修正する.
- env 削除
- CI を動かす path 追加

code-analysis の workflow を修正

---

tailwind.config.mjs

- 慣れしたんだカスタムのフォントサイズとスペーシングを作って開発できるようにする

カスタムのフォントサイズとスペーシングを定義する

---

src/app.vue
src/layouts/post.vue
src/pages/posts/[...slug].vue
src/pages/posts/[page].vue
src/pages/posts/categories/[category]/[page].vue

- 記事用に使うコンポーネントをある程度まるっと一つにおきたかったので、 記事用の NuxtLayout を用意する

記事用の NuxtLayout を用意する

---

constant/post.ts
nuxt.config.ts
src/components/post/PostList.vue
src/components/post/PostPagination.vue
src/pages/index.vue
src/pages/posts/[page].vue
src/pages/posts/categories/[category]/[page].vue

- 記事一覧のデザインを整える
- 記事一覧やページネーションのコンポーネントを作成。
- generate したあと、ページネーションが機能していなかったのも修正 [587183b](https://github.com/ume-kun1015/portofolio/pull/28/commits/587183bcfd3d2a90acfe55ce9c41922b474f6149)

記事一覧のデザインを整える

---

src/pages/[...slug].vue

存在しないパスにアクセスさせたときにホームに飛ばすように

---

nuxt.config.ts

- seo 対策をしていきたいので、一旦設定したほうがいいものを nuxt config に入れる
- htmlAttrs と charset: utf-8 を入れる

seo 関連の設定を nuxt.config に追加

---

src/pages/index.vue

- ホームで draft の記事が表示されてしまっていたので修正

ホームで draft の記事が表示されているのを修正

---

.github/workflows/code-analysis.yml

fix typo on code analysis

---

src/pages/posts/[...slug].vue

- 前後の記事に draft のものが表示されていたので、取得する条件を修正

前後の記事に draft を表示しないように

---

src/content/tech/google-photo-slack-bot.md
src/content/tech/shift-reminder.md
src/content/tech/to-rubyists-learning-golang.md
src/pages/posts/[...slug].vue

- モバイル端末で見たときに気になったデザインがあったので、修正
- カテゴリが wrap されていなかった
- 記事の中で url をそのまま貼ると 画面から overflow するので、テキストの中に埋め込む

モバイル端末で見たときに気になったデザインを修正

---

.textlintignore
src/content/tech/effective-way-to-register-external-module-func.md

- 別ファイルで定義した関数を template で効率よく使えるようにするの記事の中身を修正。
- textlint から注意されているところを修正。
- 他にも文章的におかしいところを修正

「別ファイルで定義した関数を template で効率よく使えるようにする」の修正

---

.textlintrc
package.json
pnpm-lock.yaml

- textlint を修正する上で、一時的に lint から注意されたくないものを enable / disable できるように

textlint-filter-rule-comments でマークダウンに textlint-enable / disable を使えるように

---

.textlintignore
src/content/tech/vee-validate-custom-rule.md

- VeeValidate のカスタムルールについての記事の内容を修正。lint 修正やページのリンク、文章を修正

VeeValidate のカスタムルールについての記事の内容を修正

---

.textlintignore
src/content/tech/golang-interface-tips.md

- golang の interface で知っておくとお得な tips の記事の修正。 lint で怒られていた箇条書きの部分を修正

Golang の interfaceで知っておくとお得な Tips の記事の修正

---

.textlintignore
constant/post.ts
src/content/tech/elasticsearch-tips.md

- ElasticSearch について知っておくとお得な Tips の記事の内容を修正。lint の修正が主になる。

ElasticSearch について知っておくとお得な Tips の記事の内容

---

src/content/tech/github-actions-migration.md

CI を CircleCI から GitHub Actions へ移行した記事を追加

---

src/components/post/PostList.vue
src/pages/posts/[...slug].vue
src/utils/post/category.ts

- カテゴリをパスパラメーターに変換する処理がまとまっていなく、あるところで変換がうまくできていなかったので、404 になっていた。それにより処理を共通化する

カテゴリをパスパラメーターに変換する処理を共通かする

---

src/components/post/PostList.vue

- 記事リストの投稿日時が改行されてしまっているのを修正。日時とカテゴリの行を別にする

記事リストの日時のデザイン修正

---

package.json

- cloudflare pages を使って preview ができるので、そのコマンドを用意。任意のブランチをインターネットに上げるコマンドとローカルのサーバーで表示するコマンドを用意

deploy コマンドを npm script に登録する

---

package.json

https://github.com/offich/portofolio/pull/85 でコマンドを用意したが、よく考えると内部でブランチ名を渡せることに気づいたので修正

deploy:preview コマンドの中で git ブランチ名を取得するように

---

nuxt.config.ts

Reverts offich/portofolio#86
誤って動作確認で false にするところを true にしたので、revert

Revert "末尾の trailing slash を削除する"

---

nuxt.config.ts

Reverts offich/portofolio#88
#86 の再チャレンジ。修正コミット -> [5cb8598](https://github.com/offich/portofolio/pull/90/commits/5cb85985d0b2676efb7498ff6aeed91e60ce6af4)

Revert "Revert "末尾の trailing slash を削除する""

---

src/pages/posts/[...slug].vue

- 目次があるときだけスペースを取るようにする。余分にスペースが生まれているのをなくす

目次があるときだけスペースを取るように

---

src/app.vue

- [nuxt loading indicator](https://nuxt.com/docs/api/components/nuxt-loading-indicator) を使って、ページ遷移中であることをユーザーに伝えるようにする

nuxt loading indicator を使う

---

.github/workflows/deploy-preview.yml

- 本番リリースする前に prerender や deploy コマンドが通るかどうかを確認したいので、workflow dispatch で gtihub actions での動作確認ができるようにする。

プレビュー環境へデプロイできる github actions の workflow を用意

---

.github/workflows/deploy-preview.yml

> No event triggers defined in `on` 
とエラーが出たので修正

プレビュー環境へデプロイできる github actions の workflow の修正

---

src/components/post/PostList.vue
src/pages/posts/[...slug].vue
src/pages/posts/[page].vue
src/pages/posts/categories/[category]/[page].vue
src/server/routes/sitemap.xml.ts
src/types/content.ts

- マークダウンの front matter に自由に属性を追加することができるが、その型が効かないので効かせるようにする

カスタムで追加した front matter に型を効かせるようにする

---

src/content/tech/built-portofolio-by-nuxt-content-ssg.md

- 技術構成についての記事で「ささえる技術」という文言を見かけるので、自分のブログもそのように書く

自ブログを作った記事のタイトル変更
